# SET IS COLLECTION OF UNIQUE ELEMENTS. 
# SO BY DEFAULT CURLY BRACKETS REMAINS FOR SETS.
# SETS DOES NOT FOLLOW ANY SEQUENCE.
# WHEN YOU PRINT THE SET, IT WILL PRINT SAME VALUES BUT NOT IN SAME SEQUENCE.
# IT NEITHER FOLLOW ASSENDING OR DESCENDING ORDER.
# SO, WE CAN'T DO INDEXING BECAUSE THERE IS NOT SEQUENCE 

set1 = {10,20,30,40,50,10,20,30,40,50}
print(set1)
# print(set1[0]) IT WILL SHOW ERROR...CAN NOT DO INDEXING...